DROP TABLE IF EXISTS "API";
DROP TABLE IF EXISTS "API_endpoint";
DROP TABLE IF EXISTS "API_key";
DROP TABLE IF EXISTS "User";

CREATE TABLE "API" (
    "Host" TEXT NOT NULL,
    "Name" TEXT NOT NULL DEFAULT 'INVALID_API' UNIQUE,
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE "API_key" (
    "key" TEXT NOT NULL,
    "API_ID" INTEGER NOT NULL,
    FOREIGN KEY("API_ID") REFERENCES "API"("ID") ON DELETE CASCADE,
    PRIMARY KEY("key", "API_ID")
);

CREATE TABLE "API_endpoint" (
    "endpoint" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "API_ID" INTEGER NOT NULL,
    FOREIGN KEY("API_ID") REFERENCES "API"("ID") ON DELETE CASCADE,
    PRIMARY KEY("name", "API_ID")
);

CREATE TABLE "User" (
    "ID" INTEGER NOT NULL DEFAULT 0 CHECK(ID > 0) UNIQUE,
    "AUTH_Level" INTEGER NOT NULL DEFAULT 0 CHECK(AUTH_Level > 0),
    "Name" TEXT NOT NULL DEFAULT 'INVALID_USER',
    PRIMARY KEY("ID" AUTOINCREMENT)
);
